# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

variables:
  projectDirectory: .

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- script: git clone https://github.com/JssDWt/flutter-nfc.git
  displayName: clone flutter-nfc
- task: FlutterInstall@0
- task: FlutterBuild@0
  inputs:
    target: apk
    projectDirectory: $(projectDirectory)
- task: FlutterTest@0
  inputs:
    projectDirectory: $(projectDirectory)
- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1
